on:
  push:
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        include:
          # use latest npm by default
          - npm-version: latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - name: Upgrade to latest npm to support lockfile v2
        run: npm install -g npm@${{ matrix.npm-version }}
      - run: npm install && npm install
      - run: npm run test
