on:
  push:
    branches: [main]
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
        include:
          # use latest npm by default
          - npm-version: latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - name: Upgrade to latest npm to support lockfile v2
        run: npm install -g npm@${{ matrix.npm-version }}
      - run: npm install --ignore-scripts && npm install --ignore-scripts

      # Set PUPPETEER_EXECUTABLE_PATH to the path of Chrome executable
      - name: Set Puppeteer executable path
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        run: |
          # You may need to adjust the path based on the actual location of Chrome
          # The path /usr/bin/google-chrome is an example and might not be accurate
          echo "PUPPETEER_EXECUTABLE_PATH=$PUPPETEER_EXECUTABLE_PATH" >> $GITHUB_ENV
      - run: npm run test
