on:
  release:
    types: [created]
  workflow_dispatch:
name: publish
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '16.x'
      - run: npm ci
      # Now configure with the publish service for install.
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '16.x'
          registry-url: 'https://wombat-dressing-room.appspot.com/'
      - run: npm publish --workspace packages/synthetics-sdk-api/ || npm publish --workspace packages/synthetics-sdk-mocha/ || npm publish --workspace packages/synthetics-sdk-broken-links
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
