on:
  release:
    types: [created]
  workflow_dispatch:
name: publish
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      # Now configure with the publish service for install.
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://wombat-dressing-room.appspot.com/'
      - run: npm publish --workspace packages/synthetics-sdk-api/ || npm publish --workspace packages/synthetics-sdk-mocha/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
